LOGIN_EMAIL, LOGIN_PASSWORD = range(2)

REGISTER_FULL_NAME, REGISTER_EMAIL, REGISTER_PASSWORD = range(3)

(CREATE_BOOK_TITLE, CREATE_BOOK_DESC, CREATE_BOOK_AUTHOR, CREATE_BOOK_DATE, CREATE_BOOK_LANG,
 CREATE_BOOK_CATEGORIES, CREATE_BOOK_TYPE, CREATE_BOOK_PRICE, CREATE_BOOK_IMAGE) = range(10, 19)

(MY_BOOKS_CHOOSE_ACTION, MY_BOOKS_CHOOSE_BOOK_INDEX, MY_BOOKS_CONFIRM_DELETE,
 MY_BOOKS_EDIT_TITLE, MY_BOOKS_EDIT_DESCRIPTION, MY_BOOKS_EDIT_AUTHOR,
 MY_BOOKS_EDIT_DATE, MY_BOOKS_EDIT_LANGUAGE, MY_BOOKS_EDIT_CATEGORIES,
 MY_BOOKS_EDIT_IMAGE, MY_BOOKS_EDIT_TYPE, MY_BOOKS_EDIT_PRICE) = range(20, 32)

PROFILE_WAITING_FOR_PIC = range(40, 41)

RECOMMENDATIONS_SELECTING_GENRES, RECOMMENDATIONS_SHOWING = range(50, 52)